#!/usr/bin/env python

"""This Program Start Kagisys System."""

import threading
import os


def main():
    """Main."""
    # run kagisys-info slack bot
    th_kagisys_info = threading.Thread(target=start_kagisys_info, name="kagisys_info", args=())
    th_kagisys_info.start()

    # run kansys
    th_kansys = threading.Thread(target=start_kansys, name="kansys", args=())
    th_kansys.start()
    
    # run nfc lock
    th_nfc_lock = threading.Thread(target=start_nfc_lock, name="nfc_lock", args=())
    th_nfc_lock.start()


def start_kagisys_info():
    """Start KagisysInfo Slackbot."""
    path = "/home/pi/project/kagisys_logic/kagisys_info/"
    os.chdir(path)
    os.system("sudo python2 slackbot.py")

def start_kansys():
    """Start Kansys System."""
    path = "/home/pi/project/kagisys_logic/kansys/"
    os.chdir(path)
    os.system("sudo python2 kansys.py")

def start_nfc_lock():
    """Start NFC Lock Sysytem."""
    # Move directry
    path = "/home/pi/project/kagisys_logic/nfc_lock/"
    os.chdir(path)
    os.system("sudo python2 nfc_lock.py")


if __name__ == '__main__':
    main()
